### ISSUE TITLE
Executing `which swiftlint` exited with non-zero status.

### ISSUE THREAD

**Issue by ttuygun** [ypresto/SwiftLintXcode#10]
This is the error when I encountered in Xcode 7.3.1

**Comment by ypresto** [comment]
Please ensure swiftlint binary is installed on your PATH..!

**Comment by aniforprez** [comment]
Hey I'm having the same issue. How do I do this? I installed SwiftLint with HomeBrew...

**Comment by ypresto** [comment]
Is your homebrew is placed on /usr/local..?
symlink should be placed on `/usr/local/bin/swiftlint` if you installed anywhere else.

**Comment by aniforprez** [comment]
Hey, found out that the version of swiftlint was an old one without the 'autocorrect' command. `brew update` and then `brew upgrade swiftlint` solved the issue. Thanks!
