### ISSUE TITLE
Is there plans to make this work with self signed versions of XCode 8?

### ISSUE THREAD

**Issue by haaakon** [ypresto/SwiftLintXcode#14]
I have re-signed XCode and can run plugins, is there any plans to upgrade this plugin to work with XCode 8 unsigned?

**Comment by haaakon** [comment]
@ypresto I don't think it's much work to get it to work on XCode 8, providing users have already fixed so that their XCode installation can run plugins.

**Comment by ypresto** [comment]
I'll work on it in this week..!

**Comment by haaakon** [comment]
I tried adding <string>8A66E736-A720-4B3C-92F1-33D9962C69DF</string>, and got it to build normally, but it doesn't seem to work. Seems strange, as this worked on some other plugins i use.

**Comment by ypresto** [comment]
Hmm, it seems Xcode's plugin infrastructure seems to be totally changed.
There is new ClangFormat plugin which works with Xcode 8.
https://github.com/mapbox/XcodeClangFormat/blob/34354817a4ba0813c725a22b4c1280ccdaa9e771/clang-format/Info.plist#L44
I'll investigate this.

**Comment by haaakon** [comment]
Yeah, it does seem to need more than just an adding of the UUID. Strange, because this plugin only needed that for XCode 8 support. https://github.com/ThilinaHewagama/AutoIndentWithSave

**Comment by ypresto** [comment]
![Xcode Source Editor Extension](https://cloud.githubusercontent.com/assets/400558/19315655/7a9c2e36-90d9-11e6-8ed9-8765980a405e.png)

Found this. I'll totally rewrite with this..!

**Comment by ypresto** [comment]
>  this plugin only needed that for XCode 8 support

It uses different entry point to hook save action.

https://github.com/ypresto/SwiftLintXcode/blob/7bccda576738067626d7c17621ca1d9096b6705e/SwiftLintXcode/SaveHook.swift#L27

https://github.com/ThilinaHewagama/AutoIndentWithSave/blob/f155022a46a38e63a2e55304ce848d074cf3c84c/AutoIndentWithSave/AutoIndentWithSave.m#L47

This plugin might also work with `ide_saveDocument` hook. But Xcode's future seems to be different place than unsigned one.
I'm watching this:
https://developer.apple.com/videos/play/wwdc2016/414/

**Comment by ypresto** [comment]
Finally, I decided to use `ide_saveDocument` strategy. Because:
- New plugin infra lacks "on save" hook.
- XCSourceTextBuffer does not provide file path, so making SwiftLintFramework accept String instead of File is necessary.
- I'm using XVim and I should resign anyway... :)

**Comment by ypresto** [comment]
> Yeah, it does seem to need more than just an adding of the UUID.

I tried just doing this after Swift 3 migration, and now it works like a charm..!

**Comment by ypresto** [comment]
Released v0.2.0 which works with Xcode 8..!

**Comment by AndrewSB** [comment]
@ypresto:
1. does that mean the installation instructions change? No longer do we need to code sign and then install?
2. is Alcatraz still the recommended way to install new Xcode 8 plugins?

**Comment by ypresto** [comment]
1. No, codesign **is required**. I didn't use Xcode Source Editor Extension so the plugin should be loaded directly.
2. Currently Alcatraz cannot be used without resign. So if the plugin you want to use requires resign Alcatraz is recommended, but if not Alcatraz does not support that plugin.
