### ISSUE TITLE
Read from .swiftlint.yml when autocorrecting

### ISSUE THREAD

**Issue by blau2** [ypresto/SwiftLintXcode#9]
SwiftLintXcode does not respect the rules defined in a project's `.swiftlint.yml` file. Perhaps provide the ability to optionally specify the path to the config file?

**Comment by apocolipse** [comment]
+1, I've removed this plugin until this can be fixed.

**Comment by ypresto** [comment]
Oh... It maybe bug if it is happen for v0.1.2, as I expected it to be already fixed:
https://github.com/ypresto/SwiftLintXcode/blob/ef0d9f356fe7b454bdc05b405cad0be8ecf08a22/SwiftLintXcode/Formatter.swift#L84

**Comment by brandonlau** [comment]
Ah I might have been on 0.1.1, I see that 0.1.2 came out 28 days ago which may have been right after I installed the plugin via Alcatraz. I've installed from source and it's now working as expected. Thanks!

**Comment by blau2** [comment]
Ah I might have been on 0.1.1, I see that 0.1.2 came out 28 days ago which may have been right after I installed the plugin via Alcatraz. I've installed from source and it's now working as expected. Thanks!

**Comment by ypresto** [comment]
Glad to hear that..! Thanks for reporting!
